openapi: 3.0.3
info:
  title: Sim Swap Notification Subscription
  description: |
    This API provides the customer with the ability to subscribe to event related to a sim swap operation performed on an associated phone number.

    # Introduction

    # Relevant terms and definitions

    * **SIM swap**:
    A SIM swap is a process in which a mobile phone user's current SIM card is deactivated or replaced with a new one. This is typically done by contacting the user's mobile service provider and requesting a new SIM card for various reasons, such as a lost or damaged SIM card, upgrading to a new phone, or changing phone numbers while keeping the same device.

    # API Functionality    

    The API exposes following capabilities:


    ## Sim Swap notification subscription

    Theses endpoints allow to manage notification subscription on Sim Swap event. 
    The CAMARA subscription model is detailed in the CAMARA API design guideline document and follows Cloudevents specification.

    It is mandatory in the subscription to provide the event `type` subscribed are several are managed in this API.

    Only one event ``type`` is managed for this API: 
      - ``org.camaraproject.sim-swap.v0.swapped`` - Event triggered when a sim swap occurs on the associated phoneNumber


    Note: Additionnally to these list, ``org.camaraproject.sim-swa.v0.subscription-ends`` notification `type` is sent when the subscription ends. 
    This notification did not requires dedicated subscription. 
    It is used when the subscription expire time (required by the requester) has been reached or if the API server has to terminate subscription (e.g. when the corresponding phone number is not served by the operator anymore). 

    ### Notification callback

    This endpoint describes the event notification received on subscription listener side when the event occurred. As for subscription, detailed description of the event notification is provided in the CAMARA API design guideline document.

    **WARNING**: This callback endpoint must be exposed on the listener side as `POST /{$request.body#/webhook/notificationUrl}`
      will be posted by the sim swap resource server to the webhook url provided by notification 
      listener.

    ## Further info and support

    (FAQs will be added in a later version of the documentation)

  termsOfService: http://swagger.io/terms/
  contact:
    email: project-email@sample.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.1.0-wip
externalDocs:
  description: Product documentation at CAMARA
  url: https://github.com/camaraproject/
security:
  #  - {}
  - oAuth2ClientCredentials: []
  #  - BasicAuth: []
  #  - apiKey: []
  - openId:
      - sim-swap:subscriptions:create
      - sim-swap:subscriptions:read
      - sim-swap:subscriptions:delete
servers:
  - url: '{apiRoot}/{basePath}'
    variables:
      apiRoot:
        default: http://localhost:9091
        description: API root
      basePath:
        default: /sim-swap-notification-subscriptions/v0
        description: Base path for the sim swap notification subscription API
tags:
  - name: Sim swap notification subscription
    description: Operation to manage event subscription on sim swap event (swapped)

paths:
  /subscriptions:
    post:
      tags:
        - Sim swap notification subscription
      summary: 'Create a sim swap event subscription for a phone number'
      description: Create a sim swap event subscription for a phone number
      operationId: createSimSwapSubscription
      security:
        - openId:
          - sim-swap:subscriptions:create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSubscription'
        required: true
      callbacks:
        notifications:
          "{$request.body#/webhook/notificationUrl}":
            post:
              tags:
                - Session notifications callback
              summary: "Session notifications callback"
              description: |
                Important: this endpoint is to be implemented by the API consumer.
                The sim swap server will call this endpoint whenever a swapped event occurs.
              operationId: postNotification
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      $ref: "#/components/schemas/CloudEvent"
                    examples:
                      SWAPPED:
                        $ref: '#/components/examples/SWAPPED'
                      SUBSCRIPTION_ENDS:
                        $ref: '#/components/examples/SUBSCRIPTION_ENDS'  
              responses:
                "204":
                  description: Successful notification
                "400":
                  $ref: "#/components/responses/Generic400"
                "401":
                  $ref: "#/components/responses/Generic401"
                "403":
                  $ref: "#/components/responses/Generic403"
                "500":
                  $ref: "#/components/responses/Generic500"
                "503":
                  $ref: "#/components/responses/Generic503"
              security:
                - { }
                - notificationsBearerAuth: [ ]

      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscriptionInfo'
        202 :
          description: Request accepted to be processed. It applies for async creation process.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscriptionAsync'
        400:
          $ref: '#/components/responses/Generic400'
        401:
          $ref: '#/components/responses/Generic401'
        403:
          $ref: '#/components/responses/Generic403'
        409:
          $ref: '#/components/responses/Generic409'
        500:
          $ref: '#/components/responses/Generic500'
        503:
          $ref: '#/components/responses/Generic503'
    get:
      tags:
        - Sim swap notification subscription
      summary: 'Retrieve a list of sim swap event subscription'
      description: Retrieve a list of sim swap event subscription(s)
      operationId: retrieveSubscriptionList
      security:
        - openId:
          - sim-swap:subscriptions:read
      responses:
        200:
          description: List of event subscription details
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SubscriptionInfo'
        400:
          $ref: '#/components/responses/Generic400'
        401:
          $ref: '#/components/responses/Generic401'
        403:
          $ref: '#/components/responses/Generic403'
        500:
          $ref: '#/components/responses/Generic500'
        503:
          $ref: '#/components/responses/Generic503'
  /subscriptions/{subscriptionId}:
    get:
      tags:
        - Sim swap notification subscription
      summary: 'Retrieve a sim swap event subscription for a phone number'
      operationId: retrieveSubscription
      description: retrieve event subscription information for a given subscription.
      security:
        - openId:
          - sim-swap:subscriptions:read
      parameters:
        - name: subscriptionId
          in: path
          description: Subscription identifier that was obtained from the create subscription operation
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscriptionInfo'
        400:
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorInfo"
              examples:
                Generic400:
                  summary: Schema validation failed
                  value:
                    code: INVALID_INPUT
                    status: 400
                    message: "Schema validation failed at  ..."
                subscriptionIdRequired:
                  summary: eventSubscription id is required
                  value:
                    code: INVALID_INPUT
                    status: 400
                    message: "Expected property is missing: eventSubscriptionId"
        401:
          $ref: "#/components/responses/Generic401"
        403:
          $ref: "#/components/responses/Generic403"
        404:
          $ref: "#/components/responses/Generic404"
        500:
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorInfo"
        503:
          $ref: "#/components/responses/Generic503"
    delete:
      tags:
        - Sim swap notification subscription
      summary: 'Delete a sim swap event subscription'
      operationId: deleteSubscription
      description: delete a  given event subscription.
      security:
        - openId:

          - sim-swap:subscriptions:delete
      parameters:
        - name: subscriptionId
          in: path
          description: Subscription identifier that was obtained from the create event subscription operation
          required: true
          schema:
            type: string
      responses:
        204:
          description: event subscription deleted
        202 :
          description: Request accepted to be processed. It applies for async deletion process.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscriptionAsync'
        400:
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorInfo"
              examples:
                Generic400:
                  summary: Schema validation failed
                  value:
                    code: INVALID_INPUT
                    status: 400
                    message: "Schema validation failed at  ..."
                subscriptionIdRequired:
                  summary: eventSubscription id is required
                  value:
                    code: INVALID_INPUT
                    status: 400
                    message: "Expected property is missing: eventSubscriptionId"
        401:
          $ref: "#/components/responses/Generic401"
        403:
          $ref: "#/components/responses/Generic403"
        404:
          $ref: "#/components/responses/Generic404"
        500:
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorInfo"
        503:
          $ref: "#/components/responses/Generic503"
components:
  securitySchemes:
    oAuth2ClientCredentials:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: '{tokenUrl}'
          scopes: {}
    #    BasicAuth:
    #      type: http
    #      scheme: basic
    #    apiKey:
    #      type: apiKey
    #      description: API key to authorize requests
    #      name: apikey
    #      in: query
    openId:
      type: openIdConnect
      openIdConnectUrl: https://example.com/.well-known/openid-configuration
  schemas:
    PhoneNumber:
      type: string
      pattern: '^\+?[0-9]{5,15}$'
      example: '123456789'
      description: A public identifier addressing a telephone subscription. In mobile networks it corresponds to the MSISDN (Mobile Station International Subscriber Directory Number). In order to be globally unique it has to be formatted in international format, according to E.164 standard, optionally prefixed with '+'.

    ErrorInfo:
      type: object
      required:
        - status
        - code
        - message
      properties:
        status:
          type: integer
          description: HTTP response status code
        code:
          type: string
          description: Code given to this error
        message:
          type: string
          description: Detailed error description
        
    CreateSubscription:
      description: The request for creating a sim swap event subscription
      type: object
      required:
        - webhook
        - subscriptionDetail
      properties:
        subscriptionDetail:
          $ref: '#/components/schemas/SubscriptionDetail'
        subscriptionExpireTime:
          type: string
          format: date-time
          example: 2023-01-17T13:18:23.682Z
          description: The subscription expiration time in date-time format.
        webhook:
          $ref: '#/components/schemas/Webhook'

    Webhook:
      description: Webhook information for event channel
      type: object
      required:
        - notificationUrl
      properties:
        notificationUrl:
          type: string
          example: "https://application-server.com"
          description: https callback address where the event notification must be POST-ed
        notificationAuthToken:
          type: string
          example: "c8974e592c2fa383d4a3960714"
          description: | 
            OAuth2 token to be used by the callback API endpoint. It MUST be indicated within HTTP Authorization header e.g. Authorization: Bearer $notificationAuthToken

    SubscriptionDetail:
      description: The detail of the requested event subscription
      type: object
      required:
        - type
      properties:
        phoneNumber:
          $ref: '#/components/schemas/PhoneNumber'
        type:
          $ref: '#/components/schemas/SimSwapEventType'

    SimSwapEventType:
      type: string
      description: |
        swapped - Event triggered when a sim swap was performed for this phone number

      enum:
        - org.camaraproject.sim-swap.v0.swapped

    RoamingNotificationEventType:
      type: string
      description: |
        swapped - Event triggered when a sim swap was performed for this phone number

        subscription-ends: Event triggered when the subscription ends
      enum:
        - org.camaraproject.sim-swap.v0.swapped
        - org.camaraproject.sim-swap.v0.subscription-ends

    SubscriptionInfo:
      description: Represents a sim swaps subscription.
      required:
        - startsAt
        - subscriptionId
      allOf:
        - $ref: '#/components/schemas/CreateSubscription'
        - type: object
          properties:
            subscriptionId:
              $ref: '#/components/schemas/SubscriptionId'
            startsAt:
              type: string
              format: date-time
              description: date time when subscription started
            expiresAt:
              type: string
              format: date-time
              description: date time when subscription will expire or expired
          required:
            - eventSubscriptionId
            - type

    SubscriptionAsync:
      description: Response for a sim swap operation managed asynchronously (Creation or Deletion)
      type: object
      properties:
          subscriptionId:
              $ref: '#/components/schemas/SubscriptionId'

    SubscriptionId:
      type: string
      description: The event subscription identifier.
      example: qs15-h556-rt89-1298

    CloudEvent:
      description: The notification callback
      required:
        - id
        - source
        - specversion
        - type
        - data
      properties:
        id:
          type: string
          description: identifier of this event, that must be unique in the source context.
        source:
          $ref: '#/components/schemas/Source'
        type:
          type: string
          description: 'type of event as defined in each CAMARA API'
          example: org.camaraproject.sim-swap.v0.swapped
        specversion:
          type: string
          description: Version of the specification to which this event conforms (must be 1.0 if it conforms to cloudevents 1.0.2 version)
          example: 1.0
        datacontenttype:
          type: string
          description: 'media-type that describes the event payload encoding, must be "application/json" for CAMARA APIs'
          example: application/json
        data:
          type: object
          description: Event details payload described in each CAMARA API and referenced by its type
        time:
          $ref: "#/components/schemas/DateTime"
      discriminator:
        propertyName: 'type'
        mapping:
            org.camaraproject.sim-swap.v0.swapped: '#/components/schemas/EventSimSwap'
            org.camaraproject.sim-swap.v0.subscription-ends: '#/components/schemas/EventSubscriptionEnds'

    Source:
      type: string
      format: uri-reference
      minLength: 1
      description: "Identifies the context in which an event happened in the specific Provider Implementation."
      example:
        - https://github.com/cloudevents
        - mailto:cncf-wg-serverless@lists.cncf.io
        - urn:uuid:6e8bc430-9c3a-11d9-9669-0800200c9a66
        - cloudevents/spec/pull/123
        - /sensors/tn-1234567/alerts
        - 1-555-123-4567

    DateTime:
      type: string
      format: date-time
      description: Timestamp of when the occurrence happened. Must adhere to RFC 3339.
      example: '2018-04-05T17:31:00Z'

    EventSimSwap:
      description:  event structure for swapped event
      allOf:
        - $ref: '#/components/schemas/CloudEvent'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/Swapped'

    EventSubscriptionEnds:
      description:  event structure for event subscription ends
      allOf:
        - $ref: '#/components/schemas/CloudEvent'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/SubscriptionEnds'

    Swapped:
      description: Event detail structure for ROAMING_ON & ROAMING_OFF event
      type : object
      required:
        - phoneNumber
        - subscriptionId
      properties:
        phoneNumber:
          $ref: '#/components/schemas/PhoneNumber'
        subscriptionId:
          $ref: "#/components/schemas/SubscriptionId"

    SubscriptionEnds:
      description: Event detail structure for SUBSCRIPTION_ENDS event
      type : object
      required:
        - phoneNumber
        - terminationReason
        - subscriptionId
      properties:
        phoneNumber:
          $ref: '#/components/schemas/PhoneNumber'
        terminationReason:
          type: string
          enum: ["SUBSCRIPTION_EXPIRED", "NETWORK_TERMINATED"]
        subscriptionId:
          $ref: "#/components/schemas/SubscriptionId"
        terminationDescription:
          type: string

  responses:
    Generic400:
      description: Problem with the client request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          example:
            status: 400
            code: "INVALID_ARGUMENT"
            message: "Client specified an invalid argument, request body or query param"
    Generic401:
      description: Authentication problem with the client request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          example:
            status: 401
            code: "UNAUTHENTICATED"
            message: "Request not authenticated due to missing, invalid, or expired credentials"
    Generic403:
      description: Client does not have sufficient permission
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          example:
            status: 403
            code: "PERMISSION_DENIED"
            message: "Client does not have sufficient permissions to perform this action"
    Generic404:
      description: Resource Not Found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          example:
            code: NOT_FOUND
            message: "The specified resource is not found"
    Generic409:
      description: Conflict
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          example:
            code: CONFLICT
            message: "The specified resource is in a conflict"
    Generic500:
      description: Server error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          example:
            status: 500
            code: "INTERNAL"
            message: "Server error"
    Generic503:
      description: Service unavailable. Typically the server is down.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          example:
            status: 503
            code: "UNAVAILABLE"
            message: "Service unavailable"
  examples:

    SWAPPED:
      value:
        id: 123655
        source: supertelco.notificationSendServer12
        type: org.camaraproject.sim-swap.v0.swapped
        specversion: "1.0"
        datacontenttype: application/json
        data: 
            phoneNumber: 123456788
            subscriptionId: 2ghy-55gg-7iup-yuo9
        time: 2023-01-18T13:18:23.682Z

    SUBSCRIPTION_ENDS:
      value:
        id: 123658
        source: supertelco.notificationSendServer12
        type: org.camaraproject.sim-swap.v0.subscription-ends
        specversion: "1.0"
        datacontenttype: application/json
        data: 
            phoneNumber: 123456789
            terminationReason: SUBSCRIPTION_EXPIRED
            subscriptionId: 2ghy-55gg-7iup-yuo9
            terminationDescription: subscription expire time reached
        time: 2023-01-19T13:18:23.682Z
